# Generated by Django 4.1.5 on 2023-04-11 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.product'),
        ),
    ]
